n=input("Please Enter Your Name:")
x=input("Please Enter Your Phone Number:")
p=input("Please Enter Your Date Of Birth:")
z=input("Please Enter Your Blood Group:")
a=input("Please Enter Your House Name/Apartment Name:")
print("*****************************")
print("INFORMATION")
print("*****************************")
print("Your Name Is:"+ n)
print("Your Phone Number Is:"+ x)
print("Your Date Of Birth Is:"+ p)
print("Your Blood Group Is:"+ z)
print("Your House Name/Apartment Name Is:"+ a)
print("*****************************")